### ISSUE TITLE
speed of light calculator

### ISSUE THREAD

**Issue by Jdplays** [JamesMatchett/James-Helps-Friends-Code#1]
`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace _3WayDistanceCalculator
{
    public partial class Form1 : Form
    {
        decimal time;
        decimal speedOfLight = 299792458;
        decimal distance;
        string var1;
        string var2;

        public Form1()

        {
            InitializeComponent();
            comboBox2.SelectedIndex = 0;
            comboBox1.SelectedIndex = 1;
            comboBox3.SelectedIndex = 3;
            comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            comboBox2.DropDownStyle = ComboBoxStyle.DropDownList;
            comboBox3.DropDownStyle = ComboBoxStyle.DropDownList;
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            
            if (comboBox1.SelectedItem.ToString() == "Distance" &&
               comboBox2.SelectedItem.ToString() == "Speed of light" ||
               comboBox1.SelectedItem.ToString() == "Speed of light" &&
               comboBox2.SelectedItem.ToString() == "Distance")
            {
                comboBox3.SelectedIndex = 2;
                comboBox3.Enabled = false;
            }
            else
            {
                comboBox3.Enabled = true;
            }
            if (comboBox1.SelectedItem.ToString() == "Distance" &&
               comboBox3.SelectedItem.ToString() == "Speed of light")
            {
                comboBox2.SelectedIndex = 2;
                comboBox2.Enabled = false;
            }
            else
            {
                comboBox2.Enabled = true;
            }
            
            if (comboBox1.SelectedItem.ToString() == "Distance")
            {
                label1.Text = "Distance";
            }

            if (comboBox1.SelectedItem.ToString() == "Speed of light")
            {
                label1.Text = "Speed of light";
            }

            if (comboBox1.SelectedItem.ToString() == "Time")
            {
                label1.Text = "Time";
            }

        }

        private void button1_Click(object sender, EventArgs e)
        {
            //string comb1 = Convert.ToString(comboBox1);
            //string comb2 = Convert.ToString(comboBox2);
            //if (comb1 == "Distance" && comb2 == "Speed of light")
            if (comboBox1.SelectedItem.ToString() == "Distance" && comboBox2.SelectedItem.ToString() == "Speed of light")
            {
                var1 = textBox1.Text;
                var2 = textBox2.Text;
                distance = Convert.ToDecimal(var1);
                speedOfLight = Convert.ToInt32(var2);
                time = distance / speedOfLight;
                string var3 = time.ToString() + " Seconds";
                label4.Text = var3;
            }
        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void comboBox3_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (comboBox1.SelectedItem.ToString() == "Distance" &&
                comboBox3.SelectedItem.ToString() == "Speed of light" ||
               comboBox1.SelectedItem.ToString() == "Speed of light" &&
               comboBox3.SelectedItem.ToString() == "Distance")
            {
                comboBox2.SelectedIndex = 2;
                comboBox2.Enabled = false;
            }
            else
            {
                comboBox2.Enabled = true;
            }
            if (comboBox2.SelectedItem.ToString() == "Distance" &&
               comboBox3.SelectedItem.ToString() == "Speed of light")
            {
                comboBox1.SelectedIndex = 2;
                comboBox1.Enabled = false;
            }
            else
            {
                comboBox1.Enabled = true;
            }
            

            if (comboBox3.SelectedItem.ToString() == "Distance")
            {
                label3.Text = "Distance";
            }

            if (comboBox3.SelectedItem.ToString() == "Speed of light")
            {
                label3.Text = "Speed of light";
            }

            if (comboBox3.SelectedItem.ToString() == "Time")
            {
                label3.Text = "Time";
            }
            
            
        }

        private void comboBox2_SelectedIndexChanged(object sender, EventArgs e)
        {
            
            if (comboBox2.SelectedItem.ToString() == "Distance" &&
               comboBox3.SelectedItem.ToString() == "Speed of light" ||
               comboBox2.SelectedItem.ToString() == "Speed of light" &&
               comboBox3.SelectedItem.ToString() == "Distance")
            {
                comboBox1.SelectedIndex = 2;
                comboBox1.Enabled = false;
            }
            else
            {
                comboBox2.Enabled = true;
            }
            if (comboBox2.SelectedItem.ToString() == "Distance" &&
               comboBox1.SelectedItem.ToString() == "Speed of light")
            {
                comboBox3.SelectedIndex = 2;
                comboBox3.Enabled = false;
            }
            else
            {
                comboBox3.Enabled = true;
            }
            

            if (comboBox2.SelectedItem.ToString() == "Speed of light")
            {

            }
            if (comboBox2.SelectedItem.ToString() == "Distance")
            {
                label2.Text = "Distance";
            }

            if (comboBox2.SelectedItem.ToString() == "Speed of light")
            {
                label2.Text = "Speed of light";
            }

            if (comboBox2.SelectedItem.ToString() == "Time")
            {
                label2.Text = "Time";
            }
        }
    }
}
`

**Comment by JamesMatchett** [comment]
Hey could you tell me what's specifically wrong with the code so i can get to work fixing it without having to compile it 👍 Thanks!

**Comment by JamesMatchett** [comment]
told by @Jdplays that the issue was solved, closing the issue!
