### ISSUE TITLE
Confusion Basic Concepts

### ISSUE THREAD

**Issue by LilTamaMochi** [JamesMatchett/James-Helps-Friends-Code#2]
Why does this vvv
>>>print('print("print")')

Become this vvv
>>>print("print")

also uh
how to create a concatenation?

**Comment by JamesMatchett** [comment]
I've added it just now at https://github.com/JamesMatchett/James-Helps-Friends-Code/blob/master/CJNWMusic:%20Confusion%20Basic%20Concepts%2017-09-17.py

Hope this helps :)
