### ISSUE TITLE
HELPS

### ISSUE THREAD

**Issue by FinMcLees** [JamesMatchett/James-Helps-Friends-Code#7]
[Archive.zip](https://github.com/JamesMatchett/James-Helps-Friends-Code/files/1675448/Archive.zip)
Save me

**Comment by JamesMatchett** [comment]
function factorial(num){
  var y = 0;
  for (var i=1; i<num+1; i++){
    y = y + i;
  }
  console.log('After factorial = '+(y));
  return y;
}

function getNum(y) {
  const numberOutput_span = document.getElementById('numberOutput');
  const input = document.getElementById('numberInput').value;  num = input;
 y = factorial(num); 
  numberOutput_span.innerHTML = y;
  console.log(num);
}

well first part fixed, it's now able to output a value, allbeit the wrong one but one step forward

**Comment by JamesMatchett** [comment]
function factorial(num) {
    console.log("Num is" + num);
    var y = 0;
    for (var i = 1; i <= num; i++) {
    y = y + i;
  }
  console.log('After factorial = '+(y));
  return y;
}

function getNum(y) {
  const numberOutput_span = document.getElementById('numberOutput');
  const input = document.getElementById('numberInput').value;  num = input;
  y = factorial(num)
  numberOutput_span.innerHTML = y;
  console.log(num);
}

I dont know what i did but here, it works

**Comment by JamesMatchett** [comment]
turns out what i did was when fixing the for loop, instead of it running for "num + 1" and just running for num, "num + 1" is like saying "5+1 = 51" so there's your problem :)
